server:
  port: 6038
  tomcat:
    max-http-form-post-size: 20MB

spring:
   servlet:
      multipart:
        max-request-size: 20MB
        max-file-size: 20MB

redis:
  test:
    ip: www.eee.com
    port: 6379
    user:
    password:
    db: 15
    iscluster: 0
  pro:
    ip: www.eee.com
    port: 6379
    user:
    password:
    db: 1
    iscluster: 1





