
redis:
  test: #test environment
    ip: 172.30.2.214
    port: 6379
    user: bvc
    password: YHzcGN7r532QnEyc
    db: 6
    iscluster: 0
  pre: #Pre-release environment
    ip: 172.30.2.214
    port: 6379
    user: bvc
    password: YHzcGN7r532QnEyc
    db: 6
    iscluster: 0
  pro: #Production Environment
    ip:
    port: 6379
    user:
    password:
    db: 1
    iscluster: 1


spring:
  task:
    scheduling:
      pool:
        size: 20