server:
  port: 6038


redis:
  test:
    ip: 172.30.2.214
    port: 6379
    user: bvc
    password: YHzcGN7r532QnEyc
    db: 6
    iscluster: 0
  pre:
    ip: 172.30.2.214
    port: 6379
    user: bvc
    password: YHzcGN7r532QnEyc
    db: 6
    iscluster: 0
  pro:
    ip: newlive-java.9zoaxv.clustercfg.apse1.cache.amazonaws.com
    port: 6379
    user:
    password:
    db: 1
    iscluster: 1


