FROM  centos:7

MAINTAINER privateimserver

VOLUME /privateimserver/im

RUN mkdir -p /privateimserver/im

WORKDIR /privateimserver/im

ADD jdk<version>.tar.gz /privateimserver/im


ENV JAVA_HOME /privateimserver/im/jdk<version>

ENV CLASSPATH $JAVA_HOME/lib/dt.jar:$JAVA_HOME/lib/tools.jar

ENV PATH $PATH:$JAVA_HOME/bin:$CATALINA_HOME/bin

COPY ./privateimserver-1.0.0-SNAPSHOT.jar /privateimserver/im/privateimserver-1.0.0-SNAPSHOT.jar

EXPOSE <port>

ENTRYPOINT ["nohup", "java", "-Dfile.encoding=utf-8","-Xms1024m","-Xms1024m","-jar","/privateimserver/im/privateimserver-1.0.0-SNAPSHOT.jar"]

CMD ["$@"]