#version: "1.0.0"
services:
  privateimserver:
    container_name: privateimserver
    build:
      context: ./privateimserver/im
      dockerfile: dockerfile
    ports:
      - "0.0.0.0:<port>:<port>"