server:
  port: 6038

redis:
  test:
    ip: pre-momo-redis.9zoaxv.ng.0001.apse1.cache.amazonaws.com
    port: 6379
    user:
    password:
    db: 15
    iscluster: 0
  pro:
    ip: newlive-java.9zoaxv.clustercfg.apse1.cache.amazonaws.com
    port: 6379
    user:
    password:
    db: 1
    iscluster: 1
